name: darts_link_project
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter

  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  cloud_firestore: ^4.3.1
  firebase_messaging: ^14.2.5
  firebase_storage: ^11.0.10
  flutter_local_notifications: ^13.0.0
  google_mobile_ads: ^2.3.0
  carousel_slider: ^4.2.1
  dotted_border: ^2.0.0+3
  freezed_annotation: ^2.2.0
  graphview: ^1.1.1
  json_annotation: ^4.7.0
  flutter_feather_icons: ^2.0.0+1
  uuid: ^3.0.7
  http: any
  intl: ^0.17.0
  flutter_picker: ^2.0.1
  algolia: ^1.1.2
  cupertino_icons: ^1.0.2
  multi_image_picker: ^4.8.1
  url_launcher: ^6.1.9
  firebase_dynamic_links: ^5.0.12
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  freezed: ^2.3.2
  build_runner: ^2.3.3
  json_serializable: ^6.5.4
  




flutter:
  assets:
    - assets/images/
  uses-material-design: true

